class Region {
  final String name;
  final String code;

  Region({required this.name, required this.code});
}

List<Region> regions = [
  Region(name: "United Arab Emirates", code: "ae"),
  Region(name: "Argentina", code: "ar"),
  Region(name: "Austria", code: "at"),
  Region(name: "Australia", code: "au"),
  Region(name: "Belgium", code: "be"),
  Region(name: "Bulgaria", code: "bg"),
  Region(name: "Brazil", code: "br"),
  Region(name: "Canada", code: "ca"),
  Region(name: "Switzerland", code: "ch"),
  Region(name: "China", code: "cn"),
  Region(name: "Colombia", code: "co"),
  Region(name: "Cuba", code: "cu"),
  Region(name: "Czech Republic", code: "cz"),
  Region(name: "Germany", code: "de"),
  Region(name: "Egypt", code: "eg"),
  Region(name: "France", code: "fr"),
  Region(name: "United Kingdom", code: "gb"),
  Region(name: "Greece", code: "gr"),
  Region(name: "Hong Kong", code: "hk"),
  Region(name: "Hungary", code: "hu"),
  Region(name: "Indonesia", code: "id"),
  Region(name: "Ireland", code: "ie"),
  Region(name: "Israel", code: "il"),
  Region(name: "India", code: "in"),
  Region(name: "Italy", code: "it"),
  Region(name: "Japan", code: "jp"),
  Region(name: "South Korea", code: "kr"),
  Region(name: "Lithuania", code: "lt"),
  Region(name: "Latvia", code: "lv"),
  Region(name: "Morocco", code: "ma"),
  Region(name: "Mexico", code: "mx"),
  Region(name: "Malaysia", code: "my"),
  Region(name: "Nigeria", code: "ng"),
  Region(name: "Netherlands", code: "nl"),
  Region(name: "Norway", code: "no"),
  Region(name: "New Zealand", code: "nz"),
  Region(name: "Philippines", code: "ph"),
  Region(name: "Poland", code: "pl"),
  Region(name: "Portugal", code: "pt"),
  Region(name: "Romania", code: "ro"),
  Region(name: "Serbia", code: "rs"),
  Region(name: "Russia", code: "ru"),
  Region(name: "Saudi Arabia", code: "sa"),
  Region(name: "Sweden", code: "se"),
  Region(name: "Singapore", code: "sg"),
  Region(name: "Slovenia", code: "si"),
  Region(name: "Slovakia", code: "sk"),
  Region(name: "Thailand", code: "th"),
  Region(name: "Turkey", code: "tr"),
  Region(name: "Taiwan", code: "tw"),
  Region(name: "Ukraine", code: "ua"),
  Region(name: "United States", code: "us"),
  Region(name: "Venezuela", code: "ve"),
  Region(name: "South Africa", code: "za"),
];
